clear all
close all
clc
SelLang = 2; % язык: 1-EN, 2-RU
%======================
Fs=16000;
bits=16;
num_channels=1;
numofmicrophone=1;
t_record=0.7; %время записи (сек)
play_audio=1;% если 0 - прослушать
path = 'C:\Users\Екатерина\Desktop\Диплом\Тесты муж\ши_ж.wav';
required_index = strfind(path,'\');
delimiter=required_index(end);
%======================fn2

Captions = ... % заголовки окон, кнопок etc
  {'Sound Analysis' 'Анализ звуков';... % главное окно программы
   'Load Sound Pattern' 'Загрузить эталон звука';... % кнопка 1
   'Load Investigated Sound' 'Загрузить исследуемый звук';... % кнопка 2
   'Analysis' 'Анализ';... % кнопка 3
   'Interval of Speech Signal I' 'Интервал речевого исследуемого звука ';... % график 
   'Applying a Filter' 'Применение фильтра';... % график 
   'Hamming Window' 'Окно Хемминга';... % график 
   'FFT' 'БПФ';... % график 
   '256 Amplitude Values I' '256 амплитудных значений исследуемого звука';... % график 
   '24-Element Vector I' '24-элементный вектор исследуемого звука';... % график 
   'Results:' 'Результаты:';... % текстовая метка
   'Play Sound Pattern' 'Озвучить эталон звука';... % кнопка 4
   'Play Investigated Sound' 'Озвучить исследуемый звук';... % кнопка 5
   'Record Sound' 'Записать исследуемый звук';... % кнопка 0
   'Help' 'Справка';... % кнопка 6
   'Interval of Speech Signal E','Интервал речевого эталонного звука';... % график 
   '256 Amplitude Values E','256 амплитудных значений эталонного звука';... % график 
   '24-Element Vector E','24-элементный вектор эталонного звука'}; % график 
HelpContent = ... % содержимое окна справки
  {'Методические рекомендации работы программы:';...
  '1. Нажмите кнопку «Загрузить эталон звука» - выбирите из списка запись эталона фонемы,которую хотите проверить';...
  '2. Нажмите кнопку «Озвучить эталон звука» - прослушайте запись эталона фонемы,которую хотите проверить';...
  '3. Нажмите кнопку «Записать звук» - повторите звук эталона фонемы';...
  '4. Нажмите кнопку «Анализ» - программа проанализирует произнесенный вами звук фонемы и эталон. По завершении процесса анализа выводится результат сравнения - коэффициент корреляции.';...
  'Если СR (коэффициент корреляции) меньше 0.75, то прослушайте снова исследуемый звук вернитесь в программу записи звука и повторно запишите образец звука. Если СR (коэффициент корреляции) больше 0.75, то звук произнесен правильно.'};

fn1 = 0; % имя файла звука-образца
pn1 = 0; % путь к файлу звука-образца
fn2 = 0; % имя файла исследуемого звука
pn2 = 0; % путь к файлу исследуемого звука


hFig = figure( ...  % главное окно программы
  'Position',[50 150 1000 450],...
  'Color',get(0,'DefaultUicontrolBackgroundColor'),...
  'Resize','on','MenuBar','none',...
  'NumberTitle','off','Name',Captions{1,SelLang});


hBtn0 = uicontrol(hFig,... % кнопка 0 записи звука
  'Style', 'pushbutton','String',Captions{14,SelLang},...
  'Units','normalized','Position',[0.8 0.2 0.18 0.05],...
  'Callback',['massiv=recordaudio(Fs,bits,num_channels,numofmicrophone, t_record, play_audio, path);'...
  '[fn2,pn2]=deal(path(delimiter+1:end),path(1:delimiter));'...
  'if (ischar(fn2)) set(hTxt2,''String'',fn2); end;'...
  'RunSoundAnalysis(pn1,fn1,pn2,fn2,'...
  'hTxt3,hTxt4,Captions,SelLang,0);']);

hBtnEx = uicontrol(hFig,... % кнопка выхода
  'Style', 'pushbutton','String','Выход',...
  'Units','normalized','Position',[0.8 0.1 0.18 0.05],...
  'Callback','close');

hBtn1 = uicontrol(hFig,... % кнопка 1 загрузки образца
  'Style', 'pushbutton','String',Captions{2,SelLang},...
  'Units','normalized','Position',[0.8 0.9 0.18 0.05],...
  'Callback',['[fn1,pn1]=uigetfile(''*.wav'',Captions{2,SelLang});' ...
  'if (ischar(fn1)) set(hTxt1,''String'',fn1); end;'...
  'RunSoundAnalysis(pn1,fn1,pn2,fn2,'...
  'hTxt3,hTxt4,Captions,SelLang,0);']);
hBtn4 = uicontrol(hFig,... % кнопка 4 воспроизведения образца
  'Style', 'pushbutton','String',Captions{12,SelLang},...
  'Units','normalized','Position',[0.8 0.84 0.18 0.05],...
  'Callback',['if (ischar(fn1)) '...
  '[wav,fs]=audioread([pn1 fn1]);' ...
  'soundsc(wav,fs); end;']);
hTxt1 = uicontrol(hFig,... % текст имени введённого файла
  'Style','text','Units','normalized',...
  'Position',[0.8 0.80 0.18 0.03],'String','');
hBtn2 = uicontrol(hFig,... % кнопка 2 загрузки исследуемого звука
  'Style', 'pushbutton','String',Captions{3,SelLang},...
  'Units','normalized','Position',[0.8 0.74 0.18 0.05],...
  'Callback',['[fn2,pn2]=uigetfile(''*.wav'',Captions{3,SelLang});' ...
  'if (ischar(fn2)) set(hTxt2,''String'',fn2); end;'...
  'RunSoundAnalysis(pn1,fn1,pn2,fn2,'...
  'hTxt3,hTxt4,Captions,SelLang,0);']);
hBtn5 = uicontrol(hFig,... % кнопка 2 воспроизведения исследуемого звука
  'Style', 'pushbutton','String',Captions{13,SelLang},...
  'Units','normalized','Position',[0.8 0.68 0.18 0.05],...
  'Callback',['if (ischar(fn2)) '...
  '[wav,fs]=audioread([pn2 fn2]);' ...
  'soundsc(wav,fs); end;']);
hTxt2 = uicontrol(hFig,... % текст имени введённого файла
  'Style','text','Units','normalized',...
  'Position',[0.8 0.64 0.18 0.03],'String','');
hBtn3 = uicontrol(hFig,... % кнопка 3 анализа
  'Style', 'pushbutton','String',Captions{4,SelLang},...
  'Units','normalized','Position',[0.8 0.58 0.18 0.05],...
  'Callback',['RunSoundAnalysis(pn1,fn1,pn2,fn2,'...
  'hTxt3,hTxt4,Captions,SelLang,1);']);
hBtn6 = uicontrol(hFig,... % кнопка 6 справки
  'Style', 'pushbutton','String',Captions{15,SelLang},...
  'Units','normalized','Position',[0.8 0.52 0.18 0.05],...
  'Callback','helpdlg(HelpContent,Captions{15,SelLang})');
hTxt3 = uicontrol(hFig,... % текст Результат
  'Style','text','Units','normalized',...
  'Position',[0.8 0.46 0.18 0.03],'String','');
hTxt4 = uicontrol(hFig,... % текст Коэффициент корреляции
  'Style','text','Units','normalized','HorizontalAlignment','left',...
  'Position',[0.8 0.33 0.18 0.18],'String','');




